// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkXlcuiiyqHN58XuECvgDzB1kVMur6ws',
    appId: '1:384087840161:web:5674827678b1aa86ad67e0',
    messagingSenderId: '384087840161',
    projectId: 'mytienditapp',
    authDomain: 'mytienditapp.firebaseapp.com',
    storageBucket: 'mytienditapp.appspot.com',
    measurementId: 'G-0QZRV1XEEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLOOmSkfNlkj9YUmocaoFvvE7qCve66c',
    appId: '1:384087840161:android:7306cb47941dbb4bad67e0',
    messagingSenderId: '384087840161',
    projectId: 'mytienditapp',
    storageBucket: 'mytienditapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5bvv4kxKRrnPR1mAoQhRLMS0xXLMFRjw',
    appId: '1:384087840161:ios:3f0a7825391b0e84ad67e0',
    messagingSenderId: '384087840161',
    projectId: 'mytienditapp',
    storageBucket: 'mytienditapp.appspot.com',
    iosBundleId: 'com.example.myTienditapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5bvv4kxKRrnPR1mAoQhRLMS0xXLMFRjw',
    appId: '1:384087840161:ios:3f0a7825391b0e84ad67e0',
    messagingSenderId: '384087840161',
    projectId: 'mytienditapp',
    storageBucket: 'mytienditapp.appspot.com',
    iosBundleId: 'com.example.myTienditapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNkXlcuiiyqHN58XuECvgDzB1kVMur6ws',
    appId: '1:384087840161:web:a2e4eed96e24c73cad67e0',
    messagingSenderId: '384087840161',
    projectId: 'mytienditapp',
    authDomain: 'mytienditapp.firebaseapp.com',
    storageBucket: 'mytienditapp.appspot.com',
    measurementId: 'G-EHDTK1Z6DN',
  );
}
